// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210607135942_Seed_data")]
    partial class Seed_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Topicly")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Algorithm.UserReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NegativeCount")
                        .HasColumnType("int");

                    b.Property<int>("PositiveCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Data.Models.Chats.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TopicAnswerer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicCreator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            TopicAnswerer = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreator = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -1
                        },
                        new
                        {
                            Id = -2,
                            TopicAnswerer = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreator = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -2
                        },
                        new
                        {
                            Id = -3,
                            TopicAnswerer = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreator = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -3
                        },
                        new
                        {
                            Id = -4,
                            TopicAnswerer = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreator = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -4
                        },
                        new
                        {
                            Id = -5,
                            TopicAnswerer = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreator = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -5
                        },
                        new
                        {
                            Id = -6,
                            TopicAnswerer = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreator = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -6
                        },
                        new
                        {
                            Id = -7,
                            TopicAnswerer = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreator = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -7
                        },
                        new
                        {
                            Id = -8,
                            TopicAnswerer = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreator = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -8
                        },
                        new
                        {
                            Id = -9,
                            TopicAnswerer = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreator = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -9
                        },
                        new
                        {
                            Id = -10,
                            TopicAnswerer = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreator = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -10
                        });
                });

            modelBuilder.Entity("Data.Models.Chats.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateOfSending")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = -11,
                            ChatId = -1,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 455, DateTimeKind.Unspecified).AddTicks(8687), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -12,
                            ChatId = -1,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 455, DateTimeKind.Unspecified).AddTicks(9955), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -13,
                            ChatId = -1,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(7), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -14,
                            ChatId = -1,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(38), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -15,
                            ChatId = -1,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(66), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -16,
                            ChatId = -1,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(99), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -17,
                            ChatId = -1,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(125), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -18,
                            ChatId = -1,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(151), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -19,
                            ChatId = -1,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(177), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -20,
                            ChatId = -1,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(206), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -21,
                            ChatId = -2,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(391), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -22,
                            ChatId = -2,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(419), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -23,
                            ChatId = -2,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(444), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -24,
                            ChatId = -2,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(469), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -25,
                            ChatId = -2,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(495), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -26,
                            ChatId = -2,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(520), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -27,
                            ChatId = -2,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(545), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -28,
                            ChatId = -2,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(573), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -29,
                            ChatId = -2,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(598), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -30,
                            ChatId = -2,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(623), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -31,
                            ChatId = -3,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(697), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -32,
                            ChatId = -3,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(723), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -33,
                            ChatId = -3,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(748), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -34,
                            ChatId = -3,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(815), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -35,
                            ChatId = -3,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(955), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -36,
                            ChatId = -3,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(984), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -37,
                            ChatId = -3,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1012), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -38,
                            ChatId = -3,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1041), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -39,
                            ChatId = -3,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1069), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -40,
                            ChatId = -3,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1098), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -41,
                            ChatId = -4,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1179), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -42,
                            ChatId = -4,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1208), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -43,
                            ChatId = -4,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1236), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -44,
                            ChatId = -4,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1267), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -45,
                            ChatId = -4,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1295), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -46,
                            ChatId = -4,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1324), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -47,
                            ChatId = -4,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1351), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -48,
                            ChatId = -4,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1544), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -49,
                            ChatId = -4,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1576), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -50,
                            ChatId = -4,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1606), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -51,
                            ChatId = -5,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1694), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -52,
                            ChatId = -5,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1723), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -53,
                            ChatId = -5,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1751), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -54,
                            ChatId = -5,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1871), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -55,
                            ChatId = -5,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1898), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -56,
                            ChatId = -5,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1923), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -57,
                            ChatId = -5,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1949), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -58,
                            ChatId = -5,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1975), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -59,
                            ChatId = -5,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2000), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -60,
                            ChatId = -5,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2025), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -61,
                            ChatId = -6,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2142), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -62,
                            ChatId = -6,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2168), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -63,
                            ChatId = -6,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2194), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -64,
                            ChatId = -6,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2219), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -65,
                            ChatId = -6,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2244), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -66,
                            ChatId = -6,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2270), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -67,
                            ChatId = -6,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2295), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -68,
                            ChatId = -6,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2320), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -69,
                            ChatId = -6,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2345), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -70,
                            ChatId = -6,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2370), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -71,
                            ChatId = -7,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2440), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -72,
                            ChatId = -7,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2465), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -73,
                            ChatId = -7,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2490), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -74,
                            ChatId = -7,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2557), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -75,
                            ChatId = -7,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2587), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -76,
                            ChatId = -7,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2614), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -77,
                            ChatId = -7,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2640), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -78,
                            ChatId = -7,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2665), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -79,
                            ChatId = -7,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2690), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -80,
                            ChatId = -7,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2716), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -81,
                            ChatId = -8,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2786), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -82,
                            ChatId = -8,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2811), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -83,
                            ChatId = -8,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2837), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -84,
                            ChatId = -8,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2863), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -85,
                            ChatId = -8,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2888), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -86,
                            ChatId = -8,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2913), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -87,
                            ChatId = -8,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3008), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -88,
                            ChatId = -8,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3036), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -89,
                            ChatId = -8,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3062), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -90,
                            ChatId = -8,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3088), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -91,
                            ChatId = -9,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3164), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -92,
                            ChatId = -9,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3189), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -93,
                            ChatId = -9,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3214), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -94,
                            ChatId = -9,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3265), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -95,
                            ChatId = -9,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3291), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -96,
                            ChatId = -9,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3317), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -97,
                            ChatId = -9,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3342), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -98,
                            ChatId = -9,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3368), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -99,
                            ChatId = -9,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3394), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -100,
                            ChatId = -9,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3420), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -101,
                            ChatId = -10,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3535), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -102,
                            ChatId = -10,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3561), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -103,
                            ChatId = -10,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3586), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -104,
                            ChatId = -10,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3612), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -105,
                            ChatId = -10,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3637), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -106,
                            ChatId = -10,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3663), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -107,
                            ChatId = -10,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3689), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -108,
                            ChatId = -10,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3714), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -109,
                            ChatId = -10,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3740), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -110,
                            ChatId = -10,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3765), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        });
                });

            modelBuilder.Entity("Data.Models.Topics.SeenByUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("SeenByUser");
                });

            modelBuilder.Entity("Data.Models.Topics.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 450, DateTimeKind.Unspecified).AddTicks(3700), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #0",
                            Tags = "tag2"
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(240), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-1",
                            Tags = "tag0"
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(647), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #-2",
                            Tags = "tag3"
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1125), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-3",
                            Tags = "tag2"
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(1634), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #-4",
                            Tags = "tag3"
                        },
                        new
                        {
                            Id = -6,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2048), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-5",
                            Tags = "tag3"
                        },
                        new
                        {
                            Id = -7,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2394), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #-6",
                            Tags = "tag2"
                        },
                        new
                        {
                            Id = -8,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(2739), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-7",
                            Tags = "tag0"
                        },
                        new
                        {
                            Id = -9,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3112), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #-8",
                            Tags = "tag3"
                        },
                        new
                        {
                            Id = -10,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 15, 59, 41, 456, DateTimeKind.Unspecified).AddTicks(3486), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-9",
                            Tags = "tag2"
                        });
                });

            modelBuilder.Entity("Data.Models.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "Identity");

                    b.HasData(
                        new
                        {
                            Id = "fab4fac1-c546-41de-aebc-a14da6895711",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e842d1cd-7ed9-4763-b46d-2cc89a9fcd11",
                            Email = "bob@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB@MAIL.COM",
                            NormalizedUserName = "BOB",
                            PasswordHash = "AQAAAAEAACcQAAAAECOLJmflT1ZahWptTeR8G3am9xWlAnk7C8wLDU0O01ImFpSPSvylUYGniY584K/k0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "704f96c1-43f1-4ea8-9a54-060494d6fe9d",
                            TwoFactorEnabled = false,
                            UserName = "bob"
                        },
                        new
                        {
                            Id = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae2af2eb-915f-4f28-a8b9-1af728ce4c0d",
                            Email = "alice@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE@MAIL.COM",
                            NormalizedUserName = "ALICE",
                            PasswordHash = "AQAAAAEAACcQAAAAECUs9c9M1urZRg/BLjluPTALuUGurDu6MCuL2SeZli6vh2ROflWmxuzb1jQQd2ig+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "54232939-1091-485d-8c3b-aed3c4991933",
                            TwoFactorEnabled = false,
                            UserName = "alice"
                        });
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", "Identity");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "Identity");
                });

            modelBuilder.Entity("Data.Models.Chats.Chat", b =>
                {
                    b.HasOne("Data.Models.Topics.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Data.Models.Chats.Message", b =>
                {
                    b.HasOne("Data.Models.Chats.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Data.Models.Topics.SeenByUser", b =>
                {
                    b.HasOne("Data.Models.Topics.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
