// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210607204125_ProposeNext_data")]
    partial class ProposeNext_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Topicly")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Algorithm.UserReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NegativeCount")
                        .HasColumnType("int");

                    b.Property<int>("PositiveCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Data.Models.Chats.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TopicAnswererId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopicCreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicAnswererId");

                    b.HasIndex("TopicCreatorId");

                    b.HasIndex("TopicId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            TopicAnswererId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreatorId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -1
                        },
                        new
                        {
                            Id = -2,
                            TopicAnswererId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreatorId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -2
                        },
                        new
                        {
                            Id = -3,
                            TopicAnswererId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreatorId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -3
                        },
                        new
                        {
                            Id = -4,
                            TopicAnswererId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreatorId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -4
                        },
                        new
                        {
                            Id = -5,
                            TopicAnswererId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreatorId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -5
                        },
                        new
                        {
                            Id = -6,
                            TopicAnswererId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreatorId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -6
                        },
                        new
                        {
                            Id = -7,
                            TopicAnswererId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreatorId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -7
                        },
                        new
                        {
                            Id = -8,
                            TopicAnswererId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreatorId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -8
                        },
                        new
                        {
                            Id = -9,
                            TopicAnswererId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicCreatorId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicId = -9
                        },
                        new
                        {
                            Id = -10,
                            TopicAnswererId = "fab4fac1-c546-41de-aebc-a14da6895711",
                            TopicCreatorId = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            TopicId = -10
                        });
                });

            modelBuilder.Entity("Data.Models.Chats.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateOfSending")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = -11,
                            ChatId = -1,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 581, DateTimeKind.Unspecified).AddTicks(9673), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -12,
                            ChatId = -1,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1145), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -13,
                            ChatId = -1,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1226), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -14,
                            ChatId = -1,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1272), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -15,
                            ChatId = -1,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1313), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -16,
                            ChatId = -1,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1366), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -17,
                            ChatId = -1,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1404), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -18,
                            ChatId = -1,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1442), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -19,
                            ChatId = -1,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1478), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -20,
                            ChatId = -1,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1519), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -21,
                            ChatId = -2,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1655), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -22,
                            ChatId = -2,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1693), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -23,
                            ChatId = -2,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1729), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -24,
                            ChatId = -2,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1790), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -25,
                            ChatId = -2,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1833), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -26,
                            ChatId = -2,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1869), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -27,
                            ChatId = -2,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1906), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -28,
                            ChatId = -2,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1945), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -29,
                            ChatId = -2,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1981), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -30,
                            ChatId = -2,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2017), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -31,
                            ChatId = -3,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2123), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -32,
                            ChatId = -3,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2162), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -33,
                            ChatId = -3,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2198), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -34,
                            ChatId = -3,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2236), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -35,
                            ChatId = -3,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2274), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -36,
                            ChatId = -3,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2310), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -37,
                            ChatId = -3,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2345), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -38,
                            ChatId = -3,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2391), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -39,
                            ChatId = -3,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2427), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -40,
                            ChatId = -3,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2463), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -41,
                            ChatId = -4,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2563), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -42,
                            ChatId = -4,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2601), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -43,
                            ChatId = -4,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2636), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -44,
                            ChatId = -4,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2675), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -45,
                            ChatId = -4,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2711), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -46,
                            ChatId = -4,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2746), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -47,
                            ChatId = -4,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2782), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -48,
                            ChatId = -4,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2817), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -49,
                            ChatId = -4,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2852), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -50,
                            ChatId = -4,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2887), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -51,
                            ChatId = -5,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3002), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -52,
                            ChatId = -5,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3041), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -53,
                            ChatId = -5,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3076), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -54,
                            ChatId = -5,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3112), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -55,
                            ChatId = -5,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3147), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -56,
                            ChatId = -5,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3182), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -57,
                            ChatId = -5,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3218), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -58,
                            ChatId = -5,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3253), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -59,
                            ChatId = -5,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3288), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -60,
                            ChatId = -5,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3324), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -61,
                            ChatId = -6,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3422), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -62,
                            ChatId = -6,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3460), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -63,
                            ChatId = -6,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3504), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -64,
                            ChatId = -6,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3539), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -65,
                            ChatId = -6,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3575), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -66,
                            ChatId = -6,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3610), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -67,
                            ChatId = -6,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3646), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -68,
                            ChatId = -6,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3681), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -69,
                            ChatId = -6,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3717), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -70,
                            ChatId = -6,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3752), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -71,
                            ChatId = -7,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3851), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -72,
                            ChatId = -7,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3888), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -73,
                            ChatId = -7,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3924), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -74,
                            ChatId = -7,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3959), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -75,
                            ChatId = -7,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3995), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -76,
                            ChatId = -7,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4042), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -77,
                            ChatId = -7,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4079), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -78,
                            ChatId = -7,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4114), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -79,
                            ChatId = -7,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4149), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -80,
                            ChatId = -7,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4185), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -81,
                            ChatId = -8,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4284), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -82,
                            ChatId = -8,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4322), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -83,
                            ChatId = -8,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4357), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -84,
                            ChatId = -8,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4393), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -85,
                            ChatId = -8,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4428), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -86,
                            ChatId = -8,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4463), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -87,
                            ChatId = -8,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4499), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -88,
                            ChatId = -8,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4534), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -89,
                            ChatId = -8,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4579), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -90,
                            ChatId = -8,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4615), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -91,
                            ChatId = -9,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4718), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -92,
                            ChatId = -9,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4756), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -93,
                            ChatId = -9,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4791), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -94,
                            ChatId = -9,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4855), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -95,
                            ChatId = -9,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4890), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -96,
                            ChatId = -9,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4926), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -97,
                            ChatId = -9,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4961), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -98,
                            ChatId = -9,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4997), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -99,
                            ChatId = -9,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5032), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -100,
                            ChatId = -9,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5067), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -101,
                            ChatId = -10,
                            Content = "this is test message #-1",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5181), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -102,
                            ChatId = -10,
                            Content = "this is test message #-2",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5218), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -103,
                            ChatId = -10,
                            Content = "this is test message #-3",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5254), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -104,
                            ChatId = -10,
                            Content = "this is test message #-4",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5289), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -105,
                            ChatId = -10,
                            Content = "this is test message #-5",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5324), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -106,
                            ChatId = -10,
                            Content = "this is test message #-6",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5360), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -107,
                            ChatId = -10,
                            Content = "this is test message #-7",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5395), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -108,
                            ChatId = -10,
                            Content = "this is test message #-8",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5430), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            Id = -109,
                            ChatId = -10,
                            Content = "this is test message #-9",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5466), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            Id = -110,
                            ChatId = -10,
                            Content = "this is test message #-10",
                            DateOfSending = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5501), new TimeSpan(0, 2, 0, 0, 0)),
                            SenderId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        });
                });

            modelBuilder.Entity("Data.Models.Topics.SeenByUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("SeenByUser");
                });

            modelBuilder.Entity("Data.Models.Topics.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 574, DateTimeKind.Unspecified).AddTicks(8406), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #0",
                            Tags = "tag0"
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(1566), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-1",
                            Tags = "tag2"
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2053), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #-2",
                            Tags = "tag3"
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2497), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-3",
                            Tags = "tag0"
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(2931), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #-4",
                            Tags = "tag1"
                        },
                        new
                        {
                            Id = -6,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3357), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-5",
                            Tags = "tag3"
                        },
                        new
                        {
                            Id = -7,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(3786), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #-6",
                            Tags = "tag3"
                        },
                        new
                        {
                            Id = -8,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4219), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-7",
                            Tags = "tag2"
                        },
                        new
                        {
                            Id = -9,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(4649), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            Name = "TEMAT #-8",
                            Tags = "tag2"
                        },
                        new
                        {
                            Id = -10,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 7, 22, 41, 24, 582, DateTimeKind.Unspecified).AddTicks(5101), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = "fab4fac1-c546-41de-aebc-a14da6895711",
                            Name = "TEMAT #-9",
                            Tags = "tag1"
                        });
                });

            modelBuilder.Entity("Data.Models.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "Identity");

                    b.HasData(
                        new
                        {
                            Id = "fab4fac1-c546-41de-aebc-a14da6895711",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f03b4875-3ac4-4d25-855e-0e9b8e3a40d6",
                            Email = "bob@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB@MAIL.COM",
                            NormalizedUserName = "BOB",
                            PasswordHash = "AQAAAAEAACcQAAAAEM3LjK/Iv5h36hBr0qoalEcnOk4NCMjofIPQrckF7A/g330WTksPfU6GvQARKcUbxg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b5ab7411-e238-46b7-a1cc-503554a72029",
                            TwoFactorEnabled = false,
                            UserName = "bob"
                        },
                        new
                        {
                            Id = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "16c8b42f-b77e-4e70-90ff-552cf5477c4e",
                            Email = "alice@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE@MAIL.COM",
                            NormalizedUserName = "ALICE",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLKTxGGOx29wlr9DZ/kT1UClmMnekOOY/AkEwlWOO5VxwLZgNYK2ZnuPH4mxmEZpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3bc9d145-3648-43e8-ae1e-b93a0b9a33fa",
                            TwoFactorEnabled = false,
                            UserName = "alice"
                        });
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", "Identity");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "Identity");
                });

            modelBuilder.Entity("Data.Models.Chats.Chat", b =>
                {
                    b.HasOne("Data.Models.Users.ApplicationUser", "TopicAnswerer")
                        .WithMany()
                        .HasForeignKey("TopicAnswererId");

                    b.HasOne("Data.Models.Users.ApplicationUser", "TopicCreator")
                        .WithMany()
                        .HasForeignKey("TopicCreatorId");

                    b.HasOne("Data.Models.Topics.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("TopicAnswerer");

                    b.Navigation("TopicCreator");
                });

            modelBuilder.Entity("Data.Models.Chats.Message", b =>
                {
                    b.HasOne("Data.Models.Chats.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Users.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Data.Models.Topics.SeenByUser", b =>
                {
                    b.HasOne("Data.Models.Topics.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Data.Models.Topics.Topic", b =>
                {
                    b.HasOne("Data.Models.Users.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
